#!/bin/bash
dir=$1
count=0
for entry in "$dir"/*; do

count=$((count++))

if [ -f "$entry" ]; then
echo "regular"
elif [ -d "$entry" ]; then
echo "directorio"
elif [ -L "$entry" ]; then
echo "simbolico"
elif [ -b "$entry" ]; then
echo "especial de bloque"
elif [ -c "$entry" ]; then
echo "especial caracter"
fi
done
echo "$count"
