#!/bin/bash
dir1=$1
dir2=$2

if [ $# -lt 2 ]; then
echo "Faltan parametros"
fi
if test -f "$1"
then
if test -e "$2"
then
echo "No existe ningun identificador con el nombre $2
else
echo "Existe un identificador con el nombre $2
fi
else
echo "$1 no es ordinario"
fi
