#!/bin/bash
ap1=$3
apcor1="${ap1:0:2}" ; echo "${apcor1}"
ap2=$4
apcor2="${ap2:0:2}" ; echo "${apcor2}"
nom=$2
nomcor="${nom:0:1}" ; echo "${nomcor}"
if [ $# -eq 4 ]; then
	if [ $1 == alta ]; then
	useradd "alu${apcor1}${apcor2}${nomcor}"
	groupadd "alu${apcor1}${apcor2}${nomcor}"
	usermod -a -G "alu${apcor1}${apcor2}${nomcor}" "alu${apcor1}${apcor2}${nomcor}"
	elif [ $1 == baja ]; then
	userdel "alu${apcor1}${apcor2}${nomcor}"
	groupdel "alu${apcor1}${apcor2}${nomcor}"
	else
	echo "error"
	fi
elif [ $# -eq 5 ]; then
useradd "alu${apcor1}${apcor2}${nomcor}"
usermod -a -G "alu${apcor1}${apcor2}${nomcor}" "alu${apcor1}${apcor2}${nomcor}"
else
echo "error"
fi
